version: 2.1

orbs:
    browser-tools: circleci/browser-tools@1.2.5

jobs:
  build:
    docker:
      - image: cimg/php:8.0-browsers
    environment:
      SIMPLETEST_BASE_URL: http://localhost:8888
      SIMPLETEST_DB: sqlite://localhost/tmp/db.sqlite
      SYMFONY_DEPRECATIONS_HELPER: disabled
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox", "--disable-dev-shm-usage"]}}, "http://localhost:9515"]'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install required packages
          command: |
            sudo add-apt-repository -y ppa:ondrej/php
            sudo apt update && \
            sudo apt install -y php8.0-sqlite3
      - checkout:
          path: who-stepbystep
      - run:
          name: Prepare composer from template
          command: |
            composer create-project systemseed/who-stepbystep-project drupal --no-install --stability=dev --repository="{\"url\": \"git@github.com:systemseed/who-stepbystep-project.git\", \"type\": \"vcs\"}"
      - run:
          name: Link local version of the installation profile in composer
          working_directory: drupal
          command: |
            composer config repositories.1 path ../who-stepbystep && \
            composer require "systemseed/who-stepbystep:*" --no-install && \
            composer require --dev --no-install dealerdirect/phpcodesniffer-composer-installer
      - run:
          name: Composer install
          working_directory: drupal
          command: composer install
      - run:
          name: Replace symlink with real files to build assets
          working_directory: drupal
          command: |
            rm -f web/.eslintrc.json
            rm -rf web/profiles/contrib/who-stepbystep
            cp -r ../who-stepbystep web/profiles/contrib/
      - run:
          name: Run PHP code sniffer
          working_directory: drupal
          command: |
            vendor/bin/phpcs --standard=Drupal --ignore=node_modules,vendor,dist,js,*.md web/profiles/contrib/who-stepbystep
      - run:
          name: App - Install nodejs dependencies
          working_directory: drupal/web/profiles/contrib/who-stepbystep/modules/sbs_application/js
          command: npm install
      - run:
          name: Theme - Install nodejs dependencies
          working_directory:  drupal/web/profiles/contrib/who-stepbystep/themes/material_sbs
          command: npm install
      - run:
          name: App - Run eslint
          working_directory: drupal/web/profiles/contrib/who-stepbystep/modules/sbs_application/js
          command: npm run lint
      - run:
          name: App - Build assets
          working_directory: drupal/web/profiles/contrib/who-stepbystep/modules/sbs_application/js
          command: npm run build
      - run:
          name: Theme - Build assets
          working_directory: drupal/web/profiles/contrib/who-stepbystep/themes/material_sbs
          command: npm run build
      - run:
          name: Print git status
          working_directory: drupal/web/profiles/contrib/who-stepbystep/modules/sbs_application/js
          command: git status
      - run:
          name: Fail build if there are uncommitted changes after build
          working_directory: drupal/web/profiles/contrib/who-stepbystep/modules/sbs_application/js
          command: git diff-index --quiet HEAD --
      - run:
          name: Run Drupal tests
          working_directory: drupal
          command: php -S localhost:8888 -t web/ & chromedriver --whitelisted-ips --verbose & sleep 1 && vendor/bin/phpunit -c web/core/phpunit.xml.dist web/profiles/contrib/who-stepbystep/tests
