<?php

/**
 * @file
 * Primary module hooks for SBS Users module.
 */

/**
 * Implements hook_theme_info().
 */
function sbs_users_theme($existing, $type, $theme, $path) {
  return [
    'sbs_user_profile' => [
      'variables' => [
        'participant' => NULL,
        'email' => NULL,
        'phone' => NULL,
        'profile_tabs' => NULL,
        'questionnaire_result' => '',
        'ehelpers' => [],
        'is_ehelper_requested' => FALSE,
        'answers_to_ehelper_request' => [],
      ],
    ],
    'sbs_user_activities' => [
      'variables' => [
        'activities' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function sbs_users_menu_local_tasks_alter(&$data, $route_name) {
  // Remove not needed "View" tab from user profile pages.
  if (!empty($data['tabs']) && isset($data['tabs'][0]['entity.user.canonical'])) {
    unset($data['tabs'][0]['entity.user.canonical']);
  }
}
