<?php

/**
 * @file
 * Update hooks for SBS questionnaire module.
 */

/**
 * Implements hook_install().
 */
function sbs_questionnaire_install() {
  // TODO: update Domino to make Seven configs optional.
  \Drupal::service('theme_installer')->install(['seven']);
}

/**
 * Remove all block content.
 */
function sbs_questionnaire_update_8001() {
  $blockStorage = Drupal::entityTypeManager()->getStorage('block_content');
  $blockStorage->delete($blockStorage->loadmultiple());
}
