<?php

/**
 * @file
 * Contains hooks implementation for the module.
 */

/**
 * Implements hook_theme().
 */
function sbs_user_notes_theme($existing, $type, $theme, $path) {
  return [
    'sbs_note' => [
      'variables' => [
        'author' => NULL,
        'note' => NULL,
        'created' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function sbs_user_notes_menu_local_tasks_alter(&$data, $route_name) {
  // Remove not needed "View" tab from note pages.
  if (!empty($data['tabs']) && isset($data['tabs'][0]['eck.entity_content:note.eck_canonical_tab'])) {
    unset($data['tabs'][0]['eck.entity_content:note.eck_canonical_tab']);
  }
}
